version: '3.7'
services:
  3d-print-queue-view:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - ./app/:/usr/src/app/
    environment:
      NODE_ENV: production
    command: npm start
    restart: always